name: Mirror morsh to Github

on:
  schedule:
    - cron: '0 12,00 * * *'
  workflow_dispatch:
  push:

# Ensures that only one mirror task will run at a time.
concurrency:
  group: git-mirror

jobs:
  git-mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: wearerequired/git-mirror-action@v1.2.0
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
        with:
          source-repo: "ssh://g.transcendent.ink/morsh"
          destination-repo: "git@github.com:Mia-Rain/morsh.git"
