name: Mirror psh-range to Github

on:
  schedule:
    - cron: '0 12,00 * * *'
  workflow_dispatch:
  push:

jobs:
  git-mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: wearerequired/git-mirror-action@v1.2.0
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
        with:
          source-repo: "ssh://g.transcendent.ink/psh-range"
          destination-repo: "git@github.com:Mia-Rain/psh-range.git"
